# Generated by Django 5.0.6 on 2024-06-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApp', '0003_remove_place_details_created_at_place_details_year'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place_details',
            table='place_details_tb',
        ),
    ]
