# Generated by Django 5.0.6 on 2024-06-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeApp', '0004_alter_place_details_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='founder',
            table='founder_tb',
        ),
    ]
