# Generated by Django 5.0.6 on 2024-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApp', '0005_alter_founder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_details',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
