# Generated by Django 5.0.6 on 2024-06-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApp', '0007_webinfo_place_details_web_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_details',
            name='founted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founted', to='placeApp.founder'),
        ),
    ]
