# Generated by Django 5.0.6 on 2024-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApp', '0002_founder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_details',
            name='created_at',
        ),
        migrations.AddField(
            model_name='place_details',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
